site_name: ITMO CT FAQ
nav:
  - Главная: index.md
  - FAQ:
      - 1. Самое важное: 1_base.md
      - 2. Учеба: 2_education.md
      - 3. Общежитие: 3_dormitory.md
      - 4. Прибытие в СПб: 4_arrival.md
      - 5. Медицина: 5_medicine.md
      - 6. Армия: 6_army.md
      - 7. Иностранные граждане: 7_foreigners.md
      - 8. Обучение по контракту: 8_contract.md
      - 9. Английский: 9_english.md
      - 10. Физкультура: 10_sport.md
      - 11. Стажировки и наука: 11_science.md
      - 12. Спортивное программирование: 12_icpc.md
      - 13. Электронные сервисы и департаменты ИТМО: 13_isu.md
      - 14. Студенческие возможности и бонусы: 14_bonuses.md
      - 15. Стипендии: 15_scholarship.md
      - 16. Академический отпуск, перевод, отчисление: 16_leave.md
      - 17. Сливы: 17_plums.md
  - О проекте: add.md

theme: 
    name: terminal
    features:
        - navigation.side.toc.hide

